export const CHARACTERS = {
  CHICK: '/assets/home/profile-chick.png',
  PENGUIN: '/assets/home/profile-penguin.png',
  KOALA: '/assets/home/profile-koala.png',
  COW: '/assets/home/profile-cow.png',
  TIGER: '/assets/home/profile-tiger.png',
  RABBIT: '/assets/home/profile-rabbit.png',
  CAT: '/assets/home/profile-cat.png',
  MONKEY: '/assets/home/profile-monkey.png',
  DOG: '/assets/home/profile-dog.png',
  PIG: '/assets/home/profile-pig.png',
  RAT: '/assets/home/profile-rat.png',
  BEAR: '/assets/home/profile-bear.png',
  POLARBEAR: '/assets/home/profile-polarbear.png',
  PANDA: '/assets/home/profile-panda.png',
  LION: '/assets/home/profile-lion.png',
  FOX: '/assets/home/profile-fox.png',
};

export const COLORS = {
  CHICK: '#FFF1E4',
  PENGUIN: '#E4E4E3',
  KOALA: '#C6C6C6',
  COW: '#F5F5F5',
  TIGER: '#FFECCF',
  RABBIT: '#D9EAD3',
  CAT: '#FDF2D5',
  MONKEY: '#D9EAD3',
  DOG: '#EFE2D1',
  PIG: '#FAD5FD',
  RAT: '#D9EAD3',
  BEAR: '#D2C6BB',
  POLARBEAR: '#EBD5FD',
  PANDA: '#D9EAD3',
  LION: '#FFDFD2',
  FOX: '#FCEDDC',
};
