export const CHARACTERS = [
  {key : 'CHICK ', src : "/assets/home/profile-chick.png"},
  {key : 'PENGUIN', src : "/assets/home/profile-penguin.png"},
  {key : 'KOALA', src : "/assets/home/profile-koala.png"},
  {key : 'COW', src : "/assets/home/profile-cow.png"},
  {key : 'TIGER', src : "/assets/home/profile-tiger.png"},
  {key : 'RABBIT', src : "/assets/home/profile-rabbit.png"},
  {key : 'CAT', src : "/assets/home/profile-cat.png"},
  {key : 'MONKEY', src : "/assets/home/profile-monkey.png"},
  {key : 'DOG', src : "/assets/home/profile-dog.png"},
  {key : 'PIG', src : "/assets/home/profile-pig.png"},
  {key : 'RAT', src : "/assets/home/profile-rat.png"},
  {key : 'BEAR', src : "/assets/home/profile-bear.png"},
  {key : 'POLARBEAR', src : "/assets/home/profile-polarbear.png"},
  {key : 'PANDA', src : "/assets/home/profile-panda.png"},
  {key : 'LION', src : "/assets/home/profile-lion.png"},
  {key : 'FOX', src : "/assets/home/profile-fox.png"},
];

export const COLORS = {
  CHICK: '#FFF1E4',
  PENGUIN: '#E4E4E3',
  KOALA: '#C6C6C6',
  COW: '#F5F5F5',
  TIGER: '#FFECCF',
  RABBIT: "#D9EAD3",
  CAT: "#FDF2D5",
  MONKEY: "#D9EAD3",
  DOG: "#EFE2D1",
  PIG: '#FAD5FD',
  RAT: "#D9EAD3",
  BEAR: "#D2C6BB",
  POLARBEAR: "#EBD5FD",
  PANDA: "#D9EAD3",
  LION: "#FFDFD2",
  FOX: "#FCEDDC",

};
